[general]
live_config_reload = true

[window]
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "agave", style = "Regular" }
size = 14

[cursor]
style = { shape="Block", blinking="On" }
blink_interval = 200

[colors.primary]
background = "#000000"

